function Abstract() {
    return (
        <div>
            <h1>This is the Abstract Page</h1>
            <p className='text'>The increased development and popularization of Large Language Models such as ChatGPT have overshadowed the new developments of new Topic Modeling techniques such as BERTopic. While previous research has been done with BERTopic on tweets and smaller texts, we wanted to examine BERTopic’s performance on entire books. To examine the performance of BERTopic, we decided to compare it with Latent Dirichlet allocation(LDA). We choose LDA for its status as the preferred topic modeling method for the last two decades and LDA’s bag-of-words model which contrasts with BERTopic’s use of semantic meaning through word embeddings. Experimenting with the various models included within BERTopic, we found the most effective to be the CountVectorizer. Being able to set a max document frequency, min document frequency as well as pass in a list of stopwords help reduce much of the meaningless topics. The most important choice however was choosing to split the text into approximately 500 and 1250 word size chunks. Originally we began with larger chunks of 50 paragraphs where the average word count ranged from 5,000 to 10,000, the majority of the topics appeared indecipherable or were full of names or stopwords. Running the model with 500 and 1250 word size chunks both came out very well.</p>
            <h1>victor</h1>
            <p className='alicia'>this is so fun i'm just going to write all my thoughts here so that victor can read them later even though he is probably going to delete it without reading all of it because he is lazy blah blah blah these gummy bears are such a good texture because they're soft and i don't like hard gummy bears because you can't really chew them and these are also a good size because they are small and you can eat them in one bite my favorite one is the light green one and there are also so many flavors to choose from. usually there are only like three flavors in a pack but this one has like ten it literally even has a pink one which is cool even though mine doesn't have pink. victor your keyboard was annoying at first but now it's actually kind of fun to type on because the clacking sound is satisfying even though the buttons are not thick enough so you don't feel like you're pushing down enough. what else can i talk about oh yeah i feel like i might have a cavity because when i was brushing my teeth yesterday it kind of felt sensitive on the bottom right side but also i've never had a cavity before so i don't really know if that's normal but it doesn't feel normal which is why i feel like i have a cavity. also i've been eating a lot of candy recently so i probably should go to the dentist in case i have a cavity. is a cavity like a hole in your tooth or something because now i'm realizing that i actually don't know what a cavity really is except that it hurts. ok now what else can i write about i'm running out of space but i don't know how to code so i can't make another page but actually maybe it'll just keep going down by itself automatically. i'm gonna ask victor if you can change the font on this thing becuase that would be more fun. ok well i picked a super bad font and i don't know how to change it back so i guess now i just have to deal with it bruh it's literally so ugly i don't want to look at it but also victor is working so i can't bother him to ask again to change it even though it literally hurts my eyes to look at it's so fat and ugly. now i'm just going to think of another topic to write about until jacqueline is done with her work.</p>
        </div>
    )
}

export default Abstract